export const LEFT_MOUSE_BUTTON = '1';
export const RIGHT_MOUSE_BUTTON = '2';
export const CANCEL = '3';
export const MIDDLE_MOUSE_BUTTON = '4';
export const BACKSPACE = '8';
export const TAB = '9';
export const CLEAR = '12';
export const ENTER = '13';
export const SHIFT = '16';
export const CTRL = '17';
export const ALT = '18';
export const PAUSE = '19';
export const CAPS_LOCK = '20';
export const ESC = '27';
export const SPACE = '32';
export const PAGE_UP = '33';
export const PAGE_DOWN = '34';
export const END = '35';
export const HOME = '36';
export const LEFT = '37';
export const UP = '38';
export const RIGHT = '39';
export const DOWN = '40';
export const SELECT = '41';
export const PRINT = '42';
export const EXECUTE = '43';
export const SCREENSHOT = '44';
export const INS = '45';
export const DEL = '46';
export const HELP = '47';
export const NUM0 = '48';
export const NUM1 = '49';
export const NUM2 = '50';
export const NUM3 = '51';
export const NUM4 = '52';
export const NUM5 = '53';
export const NUM6 = '54';
export const NUM7 = '55';
export const NUM8 = '56';
export const NUM9 = '57';
export const COLON = '58'; // Symbol :
export const EQUALS = '59';
export const MOZ_SEMICOLON = '59'; // Symbol ;
export const LT = '60'; // Symbol <
export const FF_EQUALS = '61';
export const BETA = '63'; // Symbol ß
export const FF_AT = '64'; // Symbol @
export const A = '65';
export const B = '66';
export const C = '67';
export const D = '68';
export const E = '69';
export const F = '70';
export const G = '71';
export const H = '72';
export const I = '73';
export const J = '74';
export const K = '75';
export const L = '76';
export const M = '77';
export const N = '78';
export const O = '79';
export const P = '80';
export const Q = '81';
export const R = '82';
export const S = '83';
export const T = '84';
export const U = '85';
export const V = '86';
export const W = '87';
export const X = '88';
export const Y = '89';
export const Z = '90';
export const LEFT_WIN = '91';
export const LEFT_COMMOND = '91';
export const RIGHT_WIN = '92';
export const MENU = '93';
export const RIGHT_COMMOND = '93';
export const NUMPAD0 = '96';
export const NUMPAD1 = '97';
export const NUMPAD2 = '98';
export const NUMPAD3 = '99';
export const NUMPAD4 = '100';
export const NUMPAD5 = '101';
export const NUMPAD6 = '102';
export const NUMPAD7 = '103';
export const NUMPAD8 = '104';
export const NUMPAD9 = '105';
export const NUMPAD_MULTIPLY = '106';
export const NUMPAD_PLUS = '107';
export const NUMPAD_ENTER_NUMPAD = '108';
export const NUMPAD_MINUS = '109';
export const NUMPAD_POINT = '110';
export const NUMPAD_DIVISION = '111';
export const F1 = '112';
export const F2 = '113';
export const F3 = '114';
export const F4 = '115';
export const F5 = '116';
export const F6 = '117';
export const F7 = '118';
export const F8 = '119';
export const F9 = '120';
export const F10 = '121';
export const F11 = '122';
export const F12 = '123';
export const F13 = '124';
export const F14 = '125';
export const F15 = '126';
export const F16 = '127';
export const F17 = '128';
export const F18 = '129';
export const F19 = '130';
export const F20 = '131';
export const F21 = '132';
export const F22 = '133';
export const F23 = '134';
export const F24 = '135';
export const NUM_LOCK = '144';
export const SCROLL_LOCK = '145';
export const CARET = '160'; // Symbol ^
export const EXCLAMATION = '161'; // Symbol !
export const HASH = '163'; // Symbol #
export const DOLLAR = '164'; // Symbol $
export const PAGE_BACKWARD = '166';
export const PAGE_FORWARD = '167';
export const ASTERISK = '170';
export const MUTE = '173';
export const FF_MINUS = '173';
export const VOL_DOWN = '174';
export const VOL_UP = '175';
export const NEXT = '176';
export const PREV = '177';
export const STOP = '178';
export const PLAY = '179';
export const EMAIL = '180';
export const FF_MUTE = '181';
export const FF_VOL_DOWN = '182';
export const FF_VOL_UP = '183';
export const SEMICOLON = '186';
export const EQUAL = '187'; // Symbol =
export const PLUS = '187';
export const COMMA = '188'; // Symbol ,
export const DASH = '189'; // Symbol -
export const MINUS = '189';
export const PERIOD = '190'; // Symbol .
export const FORWARD_SLASH = '191'; // Symbol /
export const QUESTION = '193'; // Symbol ?
export const WEBKIT_NUMPAD_PERIOD = '194';
export const OPEN_BRACKET = '219'; // Symbol [
export const BACK_SLASH = '220'; // Symbol \
export const CLOSE_BRACKET = '221'; // Symbol ]
export const SINGLE_QUOTE = '222'; // Symbol '
export const FF_COMMOND = '224';
