default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  pool: 50
  timeout: 5000

development:
  <<: *default
  database: tabletop-dev

test:
  <<: *default
  database: tabletop-test

production:
  <<: *default
  database: tabletop-prod
