# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  url: redis://localhost:6379/1
  timeout: 1

development:
  url: redis://localhost:6379/2
  timeout: 1

test:
  url: redis://localhost:6379/3
  timeout: 1
